'use strict';
const $=id=>document.getElementById(id), CAP=4;
const names=['Ana Morales','Patricia Reyes','Jorge Vallejo','M. Carmen Anguita','Tania Padilla','Cristóbal Pérez'];
let records=[{person:1,date:'2026-10-20',status:'SOLICITADO'},{person:2,date:'2026-10-20',status:'SOLICITADO'},{person:3,date:'2026-10-20',status:'SOLICITADO'},{person:4,date:'2026-10-20',status:'CONCEDIDO'},{person:5,date:'2026-10-20',status:'CONCEDIDO'},{person:4,date:'2026-10-13',status:'CONCEDIDO'}];
let month=new Date(2026,9,1),selected='',person=0,page='teacher';
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const holidays=new Set(['2026-10-12','2026-11-02','2026-12-07','2026-12-08','2027-01-06','2027-02-26','2027-03-01','2027-05-03','2027-05-28']);
const key=(y,m,d)=>`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
function off(k){let d=new Date(k+'T12:00:00Z'),w=d.getUTCDay();return w===0||w===6||holidays.has(k)||(k>='2026-12-23'&&k<='2027-01-06')||(k>='2027-03-22'&&k<='2027-03-28');}
function active(k){return records.filter(r=>r.date===k&&r.status!=='DENEGADO')}
function renderCal(id,admin){let y=month.getFullYear(),m=month.getMonth(),grid=$(id);grid.replaceChildren();$(admin?'amonth':'month').textContent=months[m]+' '+y;for(const x of ['L','M','X','J','V','S','D']){let e=document.createElement('div');e.className='weekday';e.textContent=x;grid.append(e)}for(let i=0;i<(new Date(y,m,1).getDay()+6)%7;i++)grid.append(document.createElement('div'));for(let d=1;d<=new Date(y,m+1,0).getDate();d++){let k=key(y,m,d),a=active(k),b=document.createElement('button');b.className='day'+(off(k)?' off':'')+(a.filter(r=>r.status==='CONCEDIDO').length>=CAP?' full':'')+(a.length>CAP?' conflict':'')+(k===selected&&!admin?' selected':'');b.innerHTML=`<strong>${d}</strong>`+(admin&&a.length?`<small>${a.length} solicitudes</small>`:'');b.onclick=()=>{if(admin){$('alerts').scrollIntoView({behavior:'smooth',block:'nearest'});}else{selected=k;$('chosen').textContent=new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'long',year:'numeric'}).format(new Date(k+'T12:00:00'));$('send').disabled=off(k);$('feedback').textContent=off(k)?'Día no lectivo: no se puede solicitar.':'';render()}};grid.append(b)}}
function render(){renderCal('cal',false);renderCal('acal',true);let mine=records.filter(r=>r.person===person),gr=mine.filter(r=>r.status==='CONCEDIDO').length,pe=mine.filter(r=>r.status==='SOLICITADO').length;$('available').textContent=Math.max(0,2-gr);$('pending').textContent=pe;$('granted').textContent=gr;$('mine').innerHTML=mine.map(r=>`<div class="item"><b>${r.date.split('-').reverse().join('/')}</b><span class="tag">${r.status}</span></div>`).join('')||'<p class="hint">Sin solicitudes.</p>';$('total').textContent=records.length;$('waiting').textContent=records.filter(r=>r.status==='SOLICITADO').length;let dates=[...new Set(records.map(r=>r.date))].sort(),conf=dates.filter(d=>active(d).length>CAP);$('conflicts').textContent=conf.length;$('alerts').innerHTML=conf.map(d=>`<div class="alert"><strong>${d.split('-').reverse().join('/')} · ${active(d).length} solicitudes</strong><p>Se supera el cupo de ${CAP}. Requiere valoración normativa de Dirección.</p></div>`).join('')||'<p class="hint">Sin conflictos detectados.</p>';$('all').innerHTML=records.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(r=>`<div class="item"><span>${r.date.split('-').reverse().join('/')} · ${names[r.person]}</span><span class="tag">${r.status}</span></div>`).join('')}
function switchPage(p){page=p;$('teacher').hidden=p!=='teacher';$('admin').hidden=p!=='admin';document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('on',n.dataset.page===p));$('crumb').textContent=p==='teacher'?'Mi espacio':'Centro de control';$('heading').innerHTML=p==='teacher'?'Tus días, con toda claridad<span>.</span>':'Decisiones claras, en un vistazo<span>.</span>';$('subheading').textContent=p==='teacher'?'Planifica, solicita y consulta el estado de tus permisos desde un único lugar.':'Supervisa las solicitudes, identifica concurrencias y prepara las revisiones.';render()}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>switchPage(n.dataset.page)));$('person').innerHTML=names.map((n,i)=>`<option value="${i}">${n}</option>`).join('');$('person').onchange=e=>{person=Number(e.target.value);render()};for(const [id,delta] of [['prev',-1],['next',1],['aprev',-1],['anext',1]])$(id).onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+delta,1);render()};$('send').onclick=()=>{if(!selected||off(selected))return;let mine=records.filter(r=>r.person===person&&r.status!=='DENEGADO');if(mine.some(r=>r.date===selected)){$('feedback').textContent='Ya existe una solicitud para esa fecha.';return}if(mine.length>=2){$('feedback').textContent='Ya existen dos solicitudes o concesiones activas.';return}records.push({person,date:selected,status:'SOLICITADO'});$('feedback').textContent='Solicitud ficticia registrada en esta sesión.';render()};render();
