/* PERMISOS 2D · V2 visual en laboratorio. Módulos sin dependencia del backend del centro. */
(()=>{'use strict';
const $=id=>document.getElementById(id),adapter=new DemoAdapter();
const state={route:'teacher',month:9,year:2026,userId:'u-a',selectedDate:'',caseDate:'2026-10-20',caseRequest:'S-002',data:null};
const allRoutes=['teacher','inbox','calendar','ledger','analytics'];
const escapeHtml=str=>String(str??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const user=id=>state.data.users.find(p=>p.id===id);
const rows=()=>state.data.requests;
const byDate=d=>rows().filter(r=>r.dateRequested===d);
const activeOnDate=d=>byDate(d).filter(r=>['SOLICITADO','CONCEDIDO'].includes(r.status));
const grantedOnDate=d=>byDate(d).filter(r=>r.status==='CONCEDIDO');
const conflicts=()=>[...new Set(rows().map(r=>r.dateRequested))].filter(d=>activeOnDate(d).length>DEMO_CAPACITY);
const own=()=>rows().filter(r=>r.userId===state.userId);
const userLabel=id=>escapeHtml(user(id)?.name||'Docente ficticio');
const status=s=>`<span class="status ${escapeHtml(s)}">${escapeHtml(s)}</span>`;
const dateInMonth=(y,m,d)=>`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
function resetFocusTo(button){try{button?.focus({preventScroll:true})}catch(_){}}
function renderCalendar(id,monthId,selected,onSelect){const root=$(id);root.replaceChildren();$(monthId).textContent=new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(state.year,state.month,1)));
 const start=(new Date(Date.UTC(state.year,state.month,1)).getUTCDay()+6)%7;
 for(let i=0;i<start;i++){const e=document.createElement('span');e.className='blank';root.append(e)}
 const days=new Date(Date.UTC(state.year,state.month+1,0)).getUTCDate();
 for(let n=1;n<=days;n++){const key=dateInMonth(state.year,state.month,n),requests=byDate(key),active=activeOnDate(key),off=isOff(key),isConflict=active.length>DEMO_CAPACITY;
  const button=document.createElement('button');button.type='button';button.className='calendar-day'+(off?' off':'')+(requests.length?' has-demand':'')+(isConflict?' conflict':'')+(selected===key?' selected':'');button.setAttribute('aria-label',`${prettyDate(key)}, ${off?'no lectivo en demo, ':''}${requests.length} registros, ${grantedOnDate(key).length} concedidos`);button.setAttribute('aria-pressed',String(selected===key));
  button.innerHTML=`<span class="date-number">${n}</span><span class="occupancy-dots" aria-hidden="true">${requests.slice(0,5).map(r=>`<i class="${escapeHtml(r.status)}"></i>`).join('')}</span><span class="day-count">${requests.length?requests.length+' reg.':'\u00a0'}</span>`;
  button.addEventListener('click',()=>onSelect(key));root.append(button)} }
function renderIdentity(){const teacher=state.route==='teacher';const person=user(state.userId),name=teacher?person.name:'Dirección de prueba',email=teacher?person.email:'direccion@example.invalid',parts=name.split(/\s+/).slice(0,2);$('identityName').textContent=name;$('identityRole').textContent=teacher?'Profesorado · Demostración':'Dirección · Demostración';$('identityEmail').textContent=email;$('avatar').textContent=parts.map(p=>p[0]).join('').toUpperCase();}
function renderTeacher(){const mine=own(),g=mine.filter(x=>['CONCEDIDO','DISFRUTADO'].includes(x.status)).length,p=mine.filter(x=>x.status==='SOLICITADO').length,committed=mine.filter(x=>['SOLICITADO','CONCEDIDO'].includes(x.status)).length;
 $('teacherSummary').innerHTML=`<div class="summary-item highlight"><small>POR CONCEDER · SALDO ORIENTATIVO</small><strong>${Math.max(0,DEMO_ALLOWANCE-g)} <span>/ ${DEMO_ALLOWANCE} días</span></strong><span>No refleja la disponibilidad administrativa.</span></div><div class="summary-item"><small>SOLICITUDES PENDIENTES</small><strong>${p}</strong><span>Sin resolución registrada</span></div><div class="summary-item"><small>CONCEDIDOS / COMPROMETIDOS</small><strong>${g} <span>/ ${committed}</span></strong><span>Concesiones / pendientes + concedidos</span></div>`;
 renderCalendar('teacherCalendar','teacherMonth',state.selectedDate,date=>{state.selectedDate=date;renderTeacher()});
 const d=state.selectedDate,a=d?activeOnDate(d):[],gr=d?grantedOnDate(d).length:0,duplicate=d?mine.some(r=>r.dateRequested===d&&['SOLICITADO','CONCEDIDO','DISFRUTADO'].includes(r.status)):false,blocked=!d||isOff(d)||duplicate||committed>=DEMO_ALLOWANCE;
 $('teacherSelectedTitle').textContent=d?prettyDate(d):'Selecciona una fecha';$('teacherContext').textContent=!d?'Pulsa un día del calendario para consultar su situación.':isOff(d)?'No lectivo en este calendario de demostración.':`Ocupación orientativa: ${a.length} solicitudes activas, ${gr} concesiones. ${a.length>DEMO_CAPACITY?'Hay concurrencia que debe revisarse.':''}`;
 $('teacherOccupancy').innerHTML=`<small>CUPO EXPERIMENTAL DE REFERENCIA</small><strong>${d?gr:0} / ${DEMO_CAPACITY} concedidos</strong><div class="occupancy-meter" aria-label="Cupo de ejemplo">${Array.from({length:DEMO_CAPACITY},(_,i)=>`<i class="${i<gr?'used':i<a.length?'pending':''}"></i>`).join('')}</div>`;
 const warning=duplicate?'Ya hay una solicitud propia activa para este día.':committed>=DEMO_ALLOWANCE?'Los días comprometidos alcanzan el límite experimental.':d&&isOff(d)?'Fecha no lectiva en la demostración.':'';
 $('teacherWarning').hidden=!warning;$('teacherWarning').textContent=warning;$('requestButton').disabled=blocked;
 $('personalList').innerHTML=mine.length?mine.slice().sort((a,b)=>a.dateRequested.localeCompare(b.dateRequested)).map(r=>`<div class="personal-row"><div><b>${escapeHtml(prettyDate(r.dateRequested))}</b><small>${escapeHtml(r.id)} · Solicitud de demostración</small></div>${status(r.status)}</div>`).join(''):'<p class="empty">Sin solicitudes individuales.</p>';
}
function renderCase(id,date){const r=rows().find(x=>x.id===id)||null,day=date||r?.dateRequested||state.caseDate;if(!day)return;state.caseDate=day;if(id)state.caseRequest=id;const onDay=byDate(day),current=activeOnDate(day),granted=grantedOnDate(day);
 $('caseTitle').textContent=prettyDate(day);$('caseMeta').textContent=`${onDay.length} registros en la fecha · Expediente ${r?.id||'por fecha'} · Simulación`;
 $('caseNumbers').innerHTML=[['Registradas',onDay.length],['Concedidas',granted.length],['Sin conceder',Math.max(0,DEMO_CAPACITY-granted.length)]].map(([n,v])=>`<div><strong>${v}</strong><small>${n}</small></div>`).join('');
 $('caseApplicants').innerHTML=onDay.length?onDay.map(q=>`<div class="case-person"><div><span>${userLabel(q.userId)}</span><small>${escapeHtml(q.id)} · Concedidos por docente: ${rows().filter(x=>x.userId===q.userId&&['CONCEDIDO','DISFRUTADO'].includes(x.status)).length}</small></div>${status(q.status)}</div>`).join(''):'<p class="empty">Sin registros para esta fecha.</p>';
}
function renderMetrics(){const requested=rows().filter(r=>r.status==='SOLICITADO').length,grant=rows().filter(r=>r.status==='CONCEDIDO').length,conf=conflicts().length;
 $('directorMetrics').innerHTML=[['Total de registros',rows().length,'inbox'],['Por resolver',requested,'inbox'],['Concurrencias',conf,'calendar'],['Concedidos',grant,'inbox']].map(([label,n,target])=>`<button class="director-metric" data-jump="${target}" type="button"><small>${label.toUpperCase()}</small><strong>${n}</strong><span>Abrir registros →</span></button>`).join('');
 $('directorMetrics').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{if(b.dataset.jump==='inbox'&&b.textContent.includes('Por resolver'))$('queueFilter').value='SOLICITADO';else if(b.dataset.jump==='inbox')$('queueFilter').value='ALL';route(b.dataset.jump)});
}
function renderQueue(){const q=$('queueSearch').value.trim().toLowerCase(),filter=$('queueFilter').value;const result=rows().filter(r=>(filter==='ALL'||r.status===filter)&&(!q||user(r.userId)?.name.toLowerCase().includes(q)||r.dateRequested.includes(q)||prettyDate(r.dateRequested).toLowerCase().includes(q)||r.id.toLowerCase().includes(q))).sort((a,b)=>a.dateRequested.localeCompare(b.dateRequested));
 $('queueBody').innerHTML=result.length?result.map(r=>`<tr class="${state.caseRequest===r.id?'selected-row':''}"><td>${escapeHtml(prettyDate(r.dateRequested))}</td><td><strong>${userLabel(r.userId)}</strong></td><td>${status(r.status)}</td><td><button data-case="${escapeHtml(r.id)}" type="button" aria-label="Ver expediente ${escapeHtml(r.id)}">Ver expediente ↗</button></td></tr>`).join(''):'<tr><td colspan="4">Sin solicitudes que coincidan con los filtros.</td></tr>';
 $('queueBody').querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{state.caseRequest=b.dataset.case;renderCase(state.caseRequest);renderQueue();if(window.innerWidth<1181)$('casePanel').scrollIntoView({behavior:'smooth',block:'start'})});renderCase(state.caseRequest);
}
function renderAdminCalendar(){renderCalendar('adminCalendar','adminMonth',state.caseDate,d=>{state.caseDate=d;renderAdminCalendar();renderDateContext()});renderDateContext()}
function renderDateContext(){const d=state.caseDate,all=byDate(d),gr=grantedOnDate(d),act=activeOnDate(d);$('adminDateContext').innerHTML=`<span class="eyebrow">DETALLE DE OCUPACIÓN</span><h2>${escapeHtml(prettyDate(d))}</h2><p class="muted">${isOff(d)?'Fecha no lectiva en la demo.':'Fecha de calendario demostrativo.'} · ${act.length} solicitudes activas y ${gr.length} concedidas.</p><div class="case-numbers"><div><strong>${all.length}</strong><small>Registros</small></div><div><strong>${gr.length}</strong><small>Concedidas</small></div><div><strong>${Math.max(0,DEMO_CAPACITY-gr.length)}</strong><small>Sin conceder</small></div></div>${all.length?all.map(r=>`<div class="case-person"><div>${userLabel(r.userId)}<small>${escapeHtml(r.id)}</small></div>${status(r.status)}</div>`).join(''):'<p class="empty">No hay registros en esta fecha.</p>'}<p class="legal-note">Las concurrencias no asignan prioridad ni generan resolución administrativa.</p>`}
function renderLedger(){const select=$('decisionRequest'),previous=select.value,pending=rows().filter(r=>r.status==='SOLICITADO');select.innerHTML=pending.map(r=>`<option value="${escapeHtml(r.id)}">${escapeHtml(r.id)} · ${userLabel(r.userId)} · ${escapeHtml(prettyDate(r.dateRequested))} · ${escapeHtml(r.status)}</option>`).join('');select.value=pending.some(r=>r.id===previous)?previous:(pending[0]?.id||'');select.disabled=!pending.length;$('decisionForm').querySelector('button[type="submit"]').disabled=!pending.length;if(!pending.length)$('decisionFeedback').textContent='No hay solicitudes pendientes que puedan resolverse en esta sesión.';const history=state.data.resolutions;
 $('decisionHistory').innerHTML=history.length?history.slice().reverse().map(x=>{const r=rows().find(y=>y.id===x.requestId);return`<article class="ledger-item">${status(x.outcome)} <strong>${escapeHtml(x.requestId)} · ${userLabel(r?.userId)}</strong><p>${escapeHtml(x.reason)}</p><p>Criterio: ${escapeHtml(x.rule)}${x.notes?' · '+escapeHtml(x.notes):''}</p><small>Fecha de resolución: ${escapeHtml(x.resolvedAt)} · Anterior: ${escapeHtml(x.priorStatus)} · Registro no persistente</small></article>`}).join(''):'<p class="empty">Ninguna resolución registrada durante esta sesión. Las concesiones iniciales son datos ficticios sin motivación documentada.</p>';
}
function analyticsRows(){const filter=$('periodFilter').value;return rows().filter(r=>filter==='all'||trimesters(r.dateRequested)===Number(filter))}
function barChart(id,labels,values){const max=Math.max(1,...values);$(id).innerHTML=labels.map((l,i)=>`<div class="bar-row"><span>${escapeHtml(l)}</span><div class="bar-track"><span style="width:${values[i]/max*100}%"></span></div><strong>${values[i]}</strong></div>`).join('')}
function analyticsData(){const records=analyticsRows(),dates=[...new Set(records.map(r=>r.dateRequested))],leaders=dates.map(d=>({date:d,count:records.filter(r=>r.dateRequested===d).length})).sort((a,b)=>b.count-a.count||a.date.localeCompare(b.date));const adjacent=records.filter(r=>!isOff(r.dateRequested)&&(isOff(dateAdd(r.dateRequested,-1))||isOff(dateAdd(r.dateRequested,1)))).length;const led=state.data.resolutions.filter(r=>records.some(q=>q.id===r.requestId));return{records,leaders,adjacent,ledger:led,requested:records.filter(x=>x.status==='SOLICITADO').length,granted:records.filter(x=>x.status==='CONCEDIDO').length,denied:records.filter(x=>x.status==='DENEGADO').length,conflicts:leaders.filter(x=>records.filter(r=>r.dateRequested===x.date&&['SOLICITADO','CONCEDIDO'].includes(r.status)).length>DEMO_CAPACITY).length}}
function renderAnalytics(){const d=analyticsData();$('analyticsKpis').innerHTML=[['Solicitudes',d.records.length,'Registros de demo'],['Pendientes',d.requested,'Sin resolución'],['Concurrencias',d.conflicts,'Cupo experimental'],['Denegadas',d.denied,'Estado actual']].map(([label,num,sub])=>`<div class="analytics-kpi"><small>${label}</small><strong>${num}</strong><span>${sub}</span></div>`).join('');
 const keys=['2026-09','2026-10','2026-11','2026-12','2027-01','2027-02','2027-03','2027-04','2027-05','2027-06'];barChart('monthlyChart',['Sep','Oct','Nov','Dic','Ene','Feb','Mar','Abr','May','Jun'],keys.map(x=>d.records.filter(r=>r.dateRequested.startsWith(x)).length));barChart('weekdayChart',['Lunes','Martes','Miércoles','Jueves','Viernes'],[1,2,3,4,5].map(i=>d.records.filter(r=>isoDate(r.dateRequested).getUTCDay()===i).length));
 $('topDates').innerHTML=d.leaders.length?d.leaders.slice(0,6).map(x=>`<button type="button" data-top="${escapeHtml(x.date)}" class="top-row"><span>${escapeHtml(prettyDate(x.date))}</span><strong>${x.count} registros ↗</strong></button>`).join(''):'<p class="empty">Sin fechas para mostrar.</p>';
 $('topDates').querySelectorAll('[data-top]').forEach(b=>b.onclick=()=>{state.caseDate=b.dataset.top;state.month=isoDate(state.caseDate).getUTCMonth();state.year=isoDate(state.caseDate).getUTCFullYear();route('calendar')});
 $('adjacentChart').innerHTML=`<div class="number-highlight">${d.adjacent}</div><p class="muted">de ${d.records.length} registros, en día inmediatamente anterior o posterior a un no lectivo según el calendario parcial de la demostración.</p>`;
 $('decisionChart').innerHTML=`<div class="number-highlight">${d.ledger.length}</div><p class="muted">resoluciones motivadas registradas durante la sesión. Los estados iniciales no tienen motivación asociada.</p>${d.ledger.slice(-3).map(l=>`<div class="case-person"><span>${escapeHtml(l.reason)}</span>${status(l.outcome)}</div>`).join('')}`;
 const counts=new Map();for(const l of d.ledger)counts.set(l.rule,(counts.get(l.rule)||0)+1);$('rulesChart').innerHTML=counts.size?[...counts].map(([rule,n])=>`<div class="top-row"><span>${escapeHtml(rule)}</span><strong>${n}</strong></div>`).join(''):'<p class="empty">Sin criterios documentados en esta sesión. No se puede medir su aplicación a partir del estado final.</p>';
}
function render(){renderIdentity();$('teacherView').hidden=state.route!=='teacher';$('directorView').hidden=state.route==='teacher';$('breadcrumb').textContent=({teacher:'Mi espacio',inbox:'Centro de control',calendar:'Ocupación',ledger:'Resoluciones',analytics:'Analítica y memoria'})[state.route];
 for(const b of document.querySelectorAll('[data-route]')){const active=b.dataset.route===state.route;b.classList.toggle('active',active);if(b.classList.contains('tab'))b.classList.toggle('active',active);if(b.classList.contains('side-link'))active?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')}
 for(const [name,id] of Object.entries({inbox:'inboxPage',calendar:'calendarPage',ledger:'ledgerPage',analytics:'analyticsPage'}))$(id).hidden=state.route!==name;
 if(state.route==='teacher')renderTeacher();else {const titles={inbox:['Centro de control','Prioriza expedientes, consulta concurrencias y documenta decisiones ficticias.'],calendar:['Ocupación y concurrencias','Visualiza solicitudes y concesiones en el calendario de prueba.'],ledger:['Registro de resoluciones','Documenta decisiones ficticias con motivación, fecha y criterio.'],analytics:['Analítica y memoria','Explora patrones de demanda y prepara un informe de demostración.']};const [h,p]=titles[state.route];$('directorHeading').innerHTML=escapeHtml(h)+'<span class="accent">.</span>';$('directorSubheading').textContent=p;renderMetrics();if(state.route==='inbox')renderQueue();if(state.route==='calendar')renderAdminCalendar();if(state.route==='ledger')renderLedger();if(state.route==='analytics')renderAnalytics()}}
function route(name){if(!allRoutes.includes(name))return;state.route=name;closeMenu();render();window.scrollTo({top:0,behavior:'instant'})}
function closeMenu(){$('sidebar').classList.remove('open');$('navBackdrop').hidden=true;$('menuToggle').setAttribute('aria-expanded','false')}
function openModal(){if($('requestButton').disabled)return;const d=state.selectedDate;const a=activeOnDate(d);$('modalReview').innerHTML=[['Docente',userLabel(state.userId)],['Fecha',escapeHtml(prettyDate(d))],['Solicitudes activas',String(a.length)],['Concedidas en la fecha',String(grantedOnDate(d).length)],['Naturaleza','Sin tramitación administrativa']].map(([l,v])=>`<div class="modal-review-row"><span>${l}</span><strong>${v}</strong></div>`).join('');$('requestModal').hidden=false;$('modalCancel').focus()}
function closeModal(){$('requestModal').hidden=true;resetFocusTo($('requestButton'))}
function buildReport(){
 const d=analyticsData(),period=$('periodFilter').selectedOptions[0]?.textContent||'Curso completo';
 const n=s=>d.records.filter(r=>r.status===s).length;
 const months=[['Sep','2026-09'],['Oct','2026-10'],['Nov','2026-11'],['Dic','2026-12'],['Ene','2027-01'],['Feb','2027-02'],['Mar','2027-03'],['Abr','2027-04'],['May','2027-05'],['Jun','2027-06']];
 const weekdays=['Lunes','Martes','Miércoles','Jueves','Viernes'];
 const validMonths=months.filter(([,m])=>$('periodFilter').value==='all'||trimesters(m+'-01')===Number($('periodFilter').value));
 const monthly=validMonths.map(([label,key])=>[label,d.records.filter(r=>r.dateRequested.startsWith(key)).length]);
 const weekly=weekdays.map((label,i)=>[label,d.records.filter(r=>isoDate(r.dateRequested).getUTCDay()===i+1).length]);
 const pct=d.records.length?(100*d.adjacent/d.records.length).toFixed(1).replace('.',',')+' %':'No calculable';
 const row=(a,b)=>`<tr><td>${escapeHtml(a)}</td><td class="right">${escapeHtml(b)}</td></tr>`;
 const bar=(label,value,max)=>`<div class="bar"><span>${escapeHtml(label)}</span><div class="track"><i style="width:${Math.max(0,100*value/Math.max(1,max))}%"></i></div><strong>${value}</strong></div>`;
 const maxMonth=Math.max(1,...monthly.map(x=>x[1])),maxWeek=Math.max(1,...weekly.map(x=>x[1]));
 const motifs=d.ledger.length?d.ledger.map(r=>row(r.outcome+' · '+r.reason,r.resolvedAt)).join(''):row('Sin motivos registrados en la sesión','—');
 const criteria=d.ledger.length?d.ledger.map(r=>row(r.rule,r.outcome)).join(''):row('No existen criterios documentados','—');
 const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>PERMISOS 2D · Memoria estadística de laboratorio</title><style>
 @page{size:A4;margin:14mm 16mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;font-size:10px;line-height:1.44;color:#193d47;margin:0}
 header{border-bottom:2px solid #0b6c78;padding-bottom:10px;margin-bottom:14px;display:flex;justify-content:space-between;gap:20px}header b{font-size:12px}header span{font-size:9px;color:#567780}
 h1{font-size:23px;line-height:1.15;margin:6px 0;color:#104958;letter-spacing:-.6px}h2{font-size:13px;border-bottom:1px solid #cbdeda;padding:0 0 5px;margin:17px 0 10px;color:#145b69}
 .eyebrow{text-transform:uppercase;letter-spacing:1.8px;color:#a25268;font-size:8px;font-weight:bold}
 .sub{font-size:10px;color:#58757d;margin:7px 0 12px}.warn{background:#eff6f4;border-left:3px solid #b86e72;padding:10px;margin:12px 0}
 .kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.kpi{border:1px solid #d5e3df;padding:10px;border-radius:5px;background:#f9fbfa}.kpi small{font-size:8px;color:#55757b;display:block}.kpi strong{font-size:22px;display:block;margin:4px 0;color:#0f6674}
 .cols{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel{border:1px solid #dce8e6;border-radius:5px;padding:10px}.panel h3{font-size:11px;margin:0 0 8px}.bar{display:grid;grid-template-columns:40px 1fr 18px;align-items:center;gap:6px;padding:3px 0;font-size:8px}.bar strong{text-align:right}.track{height:7px;background:#e8f0ee;border-radius:7px}.track i{display:block;background:#218391;height:100%;border-radius:7px}
 table{width:100%;border-collapse:collapse;font-size:9px}td,th{border-bottom:1px solid #dce7e5;padding:6px 6px;text-align:left;vertical-align:top}.right{text-align:right;font-weight:bold}th{background:#eef4f2}
 .pill{display:inline-block;background:#e9f4f2;border-radius:5px;color:#116878;font-size:9px;padding:8px 12px;font-weight:bold}
 .page{page-break-after:always}.page:last-child{page-break-after:auto}.foot{border-top:1px solid #dce7e5;margin-top:12px;padding-top:7px;color:#78929a;font-size:8px}
 p{margin:7px 0}.small{font-size:9px;color:#5b7c84}ul{padding-left:17px;margin:7px 0}li{margin:5px 0} .two{display:grid;grid-template-columns:1fr 1fr;gap:16px}
 </style></head><body>
 <section class="page"><header><div><b>IES VIRGEN DE LA CARIDAD · LOJA</b><br><span>PERMISOS 2D · Gestión de permisos docentes</span></div><span>LABORATORIO 2026/2027<br>INFORME FICTICIO</span></header>
 <span class="eyebrow">MEMORIA ESTADÍSTICA · DEMOSTRACIÓN</span><h1>Demanda de permisos docentes</h1><p class="sub">Periodo: ${escapeHtml(period)} · Fecha de generación: ${escapeHtml(new Date().toLocaleDateString('es-ES'))} · Fuente: DemoAdapter local</p>
 <div class="warn"><b>DOCUMENTO DE DEMOSTRACIÓN.</b> Los datos son inventados. Ninguna cifra describe al profesorado real ni una resolución administrativa.</div>
 <h2>1. Resumen ejecutivo</h2><div class="kpis"><div class="kpi"><small>REGISTROS</small><strong>${d.records.length}</strong></div><div class="kpi"><small>SOLICITADOS</small><strong>${n('SOLICITADO')}</strong></div><div class="kpi"><small>CONCEDIDOS</small><strong>${n('CONCEDIDO')}</strong></div><div class="kpi"><small>DENEGADOS</small><strong>${n('DENEGADO')}</strong></div></div>
 <p>Se observan ${d.conflicts} fechas con concurrencias que superan el umbral experimental de ${DEMO_CAPACITY} solicitudes activas. Las concesiones preexistentes permanecen intactas en la demostración.</p>
 <h2>2. Distribución temporal de las solicitudes</h2><div class="cols"><div class="panel"><h3>Por mes solicitado</h3>${monthly.map(([l,v])=>bar(l,v,maxMonth)).join('')}</div><div class="panel"><h3>Por día de la semana</h3>${weekly.map(([l,v])=>bar(l,v,maxWeek)).join('')}</div></div>
 <h2>3. Fechas más demandadas</h2><table><thead><tr><th>Fecha solicitada</th><th class="right">Registros</th></tr></thead><tbody>${d.leaders.slice(0,7).map(r=>row(prettyDate(r.date),r.count)).join('')||row('Sin datos','0')}</tbody></table>
 <div class="foot">Página 1/2 · PERMISOS 2D · No tiene valor administrativo.</div></section>
 <section class="page"><header><div><b>IES VIRGEN DE LA CARIDAD · LOJA</b><br><span>PERMISOS 2D · Memoria estadística experimental</span></div><span>CURSO 2026/2027<br>DATOS FICTICIOS</span></header>
 <span class="eyebrow">INTERPRETACIÓN Y TRAZABILIDAD</span><h1>Resoluciones y limitaciones</h1>
 <h2>4. Proximidad a días no lectivos</h2><p><span class="pill">${d.adjacent} registros · ${pct} de la muestra</span></p><p>La proporción recoge solicitudes para días marcados como lectivos que son inmediatamente anteriores o posteriores a un no lectivo según el calendario <b>parcial y ficticio</b> de la demostración. No acredita motivos personales ni establece causalidad.</p>
 <h2>5. Resoluciones motivadas durante esta sesión</h2><div class="two"><div><h3>Motivos expresamente anotados</h3><table><tbody>${motifs}</tbody></table></div><div><h3>Criterios consignados</h3><table><tbody>${criteria}</tbody></table></div></div>
 <p class="small">Resoluciones ficticias de la sesión: ${d.ledger.length}. Los estados iniciales carecen de motivación documentada. No se ha inferido que una fecha de concesión equivalga a disfrute efectivo.</p>
 <h2>6. Limitaciones de los indicadores</h2><ul><li>La agrupación trimestral utiliza la <b>fecha solicitada</b>; no la fecha de presentación, resolución o disfrute.</li><li>El calendario de demostración está incompleto; por tanto, no procede calcular tasas por día lectivo oficial ni cumplimiento de plazos legales.</li><li>El cupo ${DEMO_CAPACITY} y el saldo ${DEMO_ALLOWANCE} son hipótesis de interfaz sin valor normativo.</li><li>Las resoluciones y los datos desaparecen al cerrar o recargar la sesión. No existe auditoría institucional ni persistencia.</li></ul>
 <h2>7. Requisitos previos a una memoria institucional</h2><p>Conciliar el histórico, contrastar las disposiciones oficiales vigentes y el calendario escolar de Granada/Loja, documentar solicitudes, resoluciones motivadas y disfrutes efectivos, comprobar controles de acceso y producir un PDF institucional sometido a revisión humana.</p>
 <div class="warn"><b>Carácter del documento:</b> salida visual verificable de PERMISOS 2D. No sustituye los cauces administrativos oficiales ni Séneca cuando corresponda.</div>
 <div class="foot">Página 2/2 · Generado con datos totalmente ficticios · PERMISOS 2D.</div></section></body></html>`;
 const w=window.open('','_blank');if(!w){alert('El navegador ha bloqueado el informe imprimible. Habilita las ventanas emergentes.');return}
 w.document.open();w.document.write(html);w.document.close();w.focus();w.print()
}
async function refresh(){state.data=await adapter.getDashboard();render()}
function bindEvents(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));$('teacherSelect').onchange=async e=>{state.userId=e.target.value;state.selectedDate='';await refresh()};
 for(const [id,delta] of [['teacherPrev',-1],['teacherNext',1],['adminPrev',-1],['adminNext',1]])$(id).onclick=()=>{const v=new Date(Date.UTC(state.year,state.month+delta,1));state.year=v.getUTCFullYear();state.month=v.getUTCMonth();render()};
 $('queueSearch').oninput=renderQueue;$('queueFilter').onchange=renderQueue;$('periodFilter').onchange=renderAnalytics;$('requestButton').onclick=openModal;$('modalCancel').onclick=closeModal;document.querySelector('[data-close-modal]').onclick=closeModal;
 $('modalConfirm').onclick=async()=>{try{await adapter.requestDay({userId:state.userId,dateRequested:state.selectedDate});closeModal();await refresh()}catch(e){alert(e.message);closeModal()}};
 $('decisionDate').value='2026-10-09';$('decisionForm').onsubmit=async e=>{e.preventDefault();try{const payload={requestId:$('decisionRequest').value,outcome:$('decisionOutcome').value,resolvedAt:$('decisionDate').value,reason:$('decisionReason').value,rule:$('decisionRule').value,notes:$('decisionNotes').value};await adapter.resolveRequest(payload);$('decisionReason').value='';$('decisionRule').value='';$('decisionNotes').value='';await refresh();$('decisionFeedback').textContent='Resolución ficticia registrada únicamente en esta sesión.'}catch(err){$('decisionFeedback').textContent='No se registró la resolución: '+err.message}};
 $('printReport').onclick=buildReport;$('menuToggle').onclick=()=>{const open=$('sidebar').classList.toggle('open');$('navBackdrop').hidden=!open;$('menuToggle').setAttribute('aria-expanded',String(open))};$('navBackdrop').onclick=closeMenu;
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('requestModal').hidden)closeModal();closeMenu()}if(e.key==='Tab'&&!$('requestModal').hidden){const items=[$('modalCancel'),$('modalConfirm')];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0].focus()}}});}
async function init(){try{state.data=await adapter.getDashboard();$('teacherSelect').innerHTML=state.data.users.map(u=>`<option value="${escapeHtml(u.id)}">${escapeHtml(u.name)}</option>`).join('');$('teacherSelect').value=state.userId;bindEvents();render()}catch(e){$('main').textContent='Error al iniciar laboratorio: '+e.message;throw e}}
init();
})();
