/* Registro de resoluciones: laboratorio exclusivamente; sin persistencia ni autorización administrativa */
'use strict';
const resolutionLedger=[];
function ledgerEffectiveRows(){return entries.map((r,i)=>{const decisions=resolutionLedger.filter(x=>x.requestIndex===i);const last=decisions.at(-1);return {...r,requestIndex:i,originalStatus:r.s,s:last?last.outcome:r.s,decision:last||null};});}
function renderLedger(){const root=document.getElementById('ledgerTable');const rows=resolutionLedger.slice().reverse();root.innerHTML=rows.length?'<table><thead><tr><th>Fecha</th><th>Solicitud</th><th>Resolución</th><th>Motivo</th><th>Referencia</th></tr></thead><tbody>'+rows.map(x=>`<tr><td>${safe(x.resolvedAt)}</td><td>${safe(people[entries[x.requestIndex]?.p]||'')} · ${safe(entries[x.requestIndex]?.d||'')}</td><td>${safe(x.outcome)}</td><td>${safe(x.reason)}</td><td>${safe(x.rule)}</td></tr>`).join('')+'</tbody></table>':'<p class="a-missing">No se han registrado resoluciones adicionales en esta sesión. Las concesiones iniciales son datos ficticios heredados, sin motivo documentado.</p>';
const select=document.getElementById('ledgerRequest');const selected=select.value;select.replaceChildren();entries.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=people[r.p]+' · '+r.d+' · '+r.s;select.append(o)});select.value=selected||'0';}
function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
document.getElementById('ledgerAdd').onclick=()=>{document.getElementById('ledgerForm').hidden=false;document.getElementById('ledgerDate').value=new Date().toISOString().slice(0,10);};
document.getElementById('ledgerCancel').onclick=()=>document.getElementById('ledgerForm').hidden=true;
document.getElementById('ledgerForm').onsubmit=e=>{e.preventDefault();const id=Number(document.getElementById('ledgerRequest').value),outcome=document.getElementById('ledgerOutcome').value,reason=document.getElementById('ledgerReason').value.trim(),rule=document.getElementById('ledgerRule').value.trim(),resolvedAt=document.getElementById('ledgerDate').value,notes=document.getElementById('ledgerNotes').value.trim();if(!entries[id]||!reason||!rule||!resolvedAt)return;resolutionLedger.push({requestIndex:id,outcome,reason,rule,resolvedAt,notes,recordedAt:new Date().toISOString()});document.getElementById('ledgerForm').hidden=true;document.getElementById('ledgerFeedback').textContent='Resolución ficticia añadida al historial de esta sesión.';renderLedger();if(typeof refreshAnalytics==='function')refreshAnalytics();};
renderLedger();
